# Введение в Pandas


<a href="https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.03-Operations-in-Pandas.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>

In [33]:
import pandas as pd
pd.__version__

'1.4.3'

In [34]:
import numpy as np
np.__version__

'1.21.5'

## ```Pandas.Series```

``pandas.Series`` - это одномерный массив индексированных данных

In [35]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

``pandas.Series`` содержит последовательность значений и последовательность индексов, к которым мы можем получить доступ с помощью атрибутов ``values`` и ``index``.
Значения ``values`` - это просто знакомый нам массив NumPy:

In [36]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [37]:
data.index

RangeIndex(start=0, stop=4, step=1)

Доступ к данным можно получить по ассоциированному индексу с помощью привычной для Python нотации с квадратными скобками

In [38]:
data[1]

0.5

In [39]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### ``pandas.Series`` - обобщенный NumPy массив

In [40]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data['b']

0.5

In [41]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data[2]

0.25

### ```pandas.Series``` - специализированный словарь

In [42]:
population_dict = {
 'California': 38332521,
 'Texas'     : 26448193,
 'New York'  : 19651127,
 'Florida'   : 19552860,
 'Illinois'  : 12882135
}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [43]:
population['California']

38332521

In [44]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## ```Pandas.DataFrame```
```pandas.DataFrame``` - двумерный массив данных

### ``pandas.DataFrame`` - обобщенный NumPy массив

In [45]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area      = pd.Series(area_dict)
states    = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Прежде всего ```pandas.DataFrame``` имеет атрибут ``index``, который предоставляет доступ к меткам индекса, и атрибут ``values``, который предоставляет доступ к значениям.
Также ```pandas.DataFrame``` имеет атрибут ``columns``, который представляет собой объект ``Index``, содержащий метки столбцов

In [46]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [47]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [48]:
states.columns

Index(['population', 'area'], dtype='object')

### ```pandas.DataFrame``` - специализированный словарь

Аналогично, мы можем рассматривать ``pandas.DataFrame`` как специализацию словаря.
Если словарь связывает ключ со значением, то ``pandas.DataFrame`` связывает имя столбца с ``pandas.Series`` данных столбца.
Например, запрос атрибута `` area`` возвращает объект ``pandas.Series``

In [49]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

## Создание объектов ```pandas.DataFrame```

#### Создание из отдельного ```pandas.Series``` объекта

In [50]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### Создание из списка словарей

In [51]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [52]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### Создание из словаря, хранящего ``pandas.Series``


In [53]:
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### Создание из двумерного массива NumPy

Для двумерного массива данных, можно создать ``pandas.DataFrame`` с заданными именами колонок и индексом.

In [54]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.729701  0.956937
b  0.999480  0.501823
c  0.477605  0.375829

In [55]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [56]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## ```Pandas.Index```

Объекты ``pandas.Series`` и ``pandas.DataFrame`` содержат явный *индекс*, который позволяет ссылаться на данные и изменять их.
Объект ``pandas.Index`` можно рассматривать либо как *(immutable array) неизменяемый массив*, либо как *(ordered set) упорядоченное множество*.

In [57]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

#### ```pandas.Index``` - неизменяемый массив

In [58]:
ind[1]

3

In [59]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [60]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [61]:
ind[1] = 0

TypeError: Index does not support mutable operations

### ``pandas.Index`` - упорядоченное множество

In [62]:
index_A = pd.Index([1, 3, 5, 7,  9])
index_B = pd.Index([2, 3, 5, 7, 11])

In [63]:
index_A & index_B  # пересечение

/tmp/ipykernel_17482/391748823.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  index_A & index_B  # пересечение


Int64Index([3, 5, 7], dtype='int64')

In [64]:
index_A | index_B  # объединение

/tmp/ipykernel_17482/3091286000.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  index_A | index_B  # объединение


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [65]:
index_A ^ index_B  # симметричная разность

/tmp/ipykernel_17482/429078548.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  index_A ^ index_B  # симметричная разность


Int64Index([1, 2, 9, 11], dtype='int64')

# Индексирование и извлечение данных

## Извлечение данных ``pandas.Series``

### ``pandas.Series`` - словарь
Объект ``pandas.Series`` обеспечивает отображение коллекции ключей на коллекцию значений

In [66]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [67]:
data['b']

0.5

Методы и выражения для обработки ключей/индексов и значений в *dictionary-like* стиле

In [68]:
'a' in data

True

In [69]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [70]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### ``pandas.Series`` - одномерный массив

``pandas.Series`` объект обеспечивает выбор элементов в стиле массива с помощью тех же основных механизмов, что и массивы NumPy - то есть, *slices (сечения)*, *masking (маскирование)*, and *fancy indexing*.

In [71]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [72]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [73]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [74]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Indexers: loc и iloc

Рассмотрим следующий пример: ``pandas.Series`` имеет явный целочисленный индекс, операция индексирования, такая как ``data[1]``, будет использовать явный индекс, а операция сечения, такая как ``data[1:3]``, будет использовать неявный индекс в стиле Python.

In [75]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [76]:
# explicit index when indexing
data[1]

'a'

In [77]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Поскольку в случае использования целочисленных индексов возникает потенциальная путаница, ``Pandas`` предоставляет некоторые специальные атрибуты *indexer*, которые явно раскрывают определенные схемы индексирования.
Это не функциональные методы, а атрибуты, которые открывают определенный интерфейс доступа к данным в ``pandas.Series``.
Во-первых, атрибут ``loc`` позволяет индексировать и нарезать данные, которые всегда ссылаются на явный индекс объекта

In [78]:
data.loc[1]

'a'

In [79]:
data.loc[1:3]

1    a
3    b
dtype: object

Атрибут ``iloc`` позволяет индексировать и нарезать, используя индекс в стиле Python

In [80]:
data.iloc[1]

'b'

In [81]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Извлечение данных ``pandas.DataFrame``

Напомним, что ``pandas.DataFrame`` во многом похож на двумерный или структурированный массив, а в чем-то - на словарь структур ``pandas.Series``, имеющих один и тот же индекс.

### ``pandas.DataFrame`` - словарь

In [100]:
area = pd.Series({'California': 423967  ,'Texas': 695662  ,'New York': 141297  , 'Florida': 170312  ,'Illinois': 149995  })
pop  = pd.Series({'California': 38332521,'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Доступ к отдельным ``pandas.Series'', составляющим столбцы ``pandas.DataFrame``, можно получить с помощью индексации по названию столбца в стиле словаря

In [101]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [102]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [103]:
data.area is data['area']

True

In [104]:
data.pop is data['pop']

False

In [105]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### ``pandas.DataFrame`` - двумерный массив

Можно изучить массив данных, используя атрибут ``values''

In [106]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

Можно транспонировать ``pandas.DataFrame`` , поменять местами строки и столбцы

In [107]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

``pandas.DataFrame`` индексация столбцов в стиле словаря не позволяет нам просто обращаться с данными, как с массивами NumPy. 

Передача одного индекса в массив дает доступ к строке

In [108]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

Передача единственного "индекса" в ``pandas,DataFrame`` обеспечивает доступ к столбцу

In [109]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Таким образом, для индексации в стиле массива нам требуется другое соглашение.
Здесь Pandas снова использует индексаторы ``loc``, ``iloc``.
Используя индексатор ``iloc``, мы можем индексировать базовый массив, как если бы это был простой массив NumPy (используя неявный индекс в стиле Python), но индекс ``DataFrame`` и метки столбцов сохраняются в результате

In [113]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [114]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [117]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [118]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Дополнительные соглашения об индексации

Существует несколько дополнительных соглашений по индексированию, которые могут показаться противоречащими предыдущему обсуждению, но, тем не менее, могут быть очень полезны на практике.
Во-первых, в то время как *indexing (индексирование)* относится к столбцам, *slicing (сечение)* относится к строкам

In [119]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [120]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

Операции маскирования также интерпретируются по строкам, а не по столбцам

In [122]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# Работа с данными в Pandas

Одним из важнейших элементов NumPy является возможность быстрого выполнения операций с элементами, как с базовой арифметикой (сложение, вычитание, умножение и т.д.), так и с более сложными операциями (тригонометрические функции, экспоненциальные и логарифмические функции и т.д.).
Pandas унаследовал большую часть этой функциональности от NumPy, а Ufuncs, являются ключом к этому.

Однако Pandas включает в себя пару полезных поворотов: для унарных операций, таких как отрицание и тригонометрические функции, эти Ufuncs будут *сохранять метки индексов и столбцов* на выходе, а для бинарных операций, таких как сложение и умножение, Pandas будет автоматически *выравнивать индексы* при передаче объектов в ufunc.
Это означает, что сохранение контекста данных и объединение данных из разных источников - обе потенциально опасные задачи с необработанными массивами NumPy - становятся практически безошибочными с Pandas.
Кроме того, мы увидим, что существуют четко определенные операции между одномерными структурами ``Series'' и двумерными структурами ``DataFrame''.

## Ufuncs: Сохранение индексов

Поскольку Pandas разработан для работы с NumPy, любая ufunc NumPy будет работать с объектами Pandas ``pandas.Series`` и ``pandas.DataFrame``.
Определим простые ``pandas.Series`` и ``pandas.DataFrame``

In [123]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [124]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [125]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [126]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## UFuncs: Выравнивание индексов

Для бинарных операций над двумя объектами ``pandas.Series`` или ``pandas.DataFrame`` Pandas выравнивает индексы в процессе выполнения операции.
Это очень удобно при работе с неполными данными.

### Выравнивание индекса ``pandas.Series``

In [129]:
area       = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [128]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [130]:
area.index | population.index

/tmp/ipykernel_17482/3572280633.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [131]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [132]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Выравнивание индекса ``pandas.DataFrame``

In [133]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [134]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [135]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [137]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


## Ufuncs: Операции между ``pandas.DataFrame`` и ``pandas.Series``

При выполнении операций между ``pandas.DataFrame`` и ``pandas.Series`` аналогично сохраняется выравнивание индексов и столбцов.
Операции между ``pandas.DataFrame`` и ``pandas.Series`` похожи на операции между двумерным и одномерным массивом NumPy.
Рассмотрим одну общую операцию, в которой мы находим разность двумерного массива и одной из его строк:

In [138]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [139]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [140]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [141]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [142]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [143]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

# Handling Missing Data

# Hierarchical Indexing

# Combining Datasets: Concat and Append

# Combining Datasets: Merge and Join

# Aggregation and Grouping

# Pivot Tables